### ISSUE TITLE
Update to 1.16.4

### ISSUE THREAD

**Issue by Blueil** [gnembon/carpet-autoCraftingTable#11]
I want to use this feature for survival 1.16.4 but currently if I use the 1.16.3 version it's just disabling the crafting table, please update.

**Comment by altrisi** [comment]
The 1.16.4 was released 8 days ago. You have it [here](https://github.com/gnembon/carpet-autoCraftingTable/releases/tag/v1.4).

**Comment by TijmenSpijk** [comment]
Downloading and installing the 1.16.4 version into my mod folder disables the craftingtable and doesn't add any hopper support.
Carpet works fine. No other mods installed other than fabric api.

**Comment by gnembon** [comment]
hmm, I checked without the fabric API, can check again.

If you try without Fabric API and it works, please let me know. It may also be a matter of breaking and replacing the crafting table.

**Comment by TijmenSpijk** [comment]
Tried a fresh install of fabric and with only fabric-carpet and carpet-autocrafting as mods. Created a new world and it doesn't work.
I deleted all traces of the other mods i used but it still doesn't work.

**Comment by gnembon** [comment]
Ok - can replicate myself. Will look into that

**Comment by gnembon** [comment]
you have to have crafting table enabled to have the crafting table to work at all. `/carpet autoCraftingTable true` .Also disabling it doesn't disable it as well.
I assume you install it to use it so its not that big of a deal, but will check whats up with that

**Comment by TijmenSpijk** [comment]
I see what i did wrong. I needed to enable autocrafting via a command. Maybe add this to the readme so people dont miss this step.

**Comment by gnembon** [comment]
Ok, figure out the issue - its in releases as build2
