### ISSUE TITLE
Easy dupe with crafting table in unloaded chunk

### ISSUE THREAD

**Issue by NikitaCartes** [gnembon/carpet-autoCraftingTable#18]
Reproduction steps:
1) Place items in crafting table
2) Get into minecart and start leaving
3) Open crafting table while you'rу close to it (First screenshot)
4) Drive long distance (~500 blocks on server with view-distance=16) and pick up items from crafting table (Second screenshot)
5) Go back to crafting table and find two copies of the items: in inventory and crafting table (Third screenshot)

![image](https://user-images.githubusercontent.com/18899227/103387095-01b47e80-4b13-11eb-8081-1636aa1d8fc6.png)
![image](https://user-images.githubusercontent.com/18899227/103387102-09742300-4b13-11eb-8ff1-a52ad6eeeec9.png)
![image](https://user-images.githubusercontent.com/18899227/103387122-26105b00-4b13-11eb-8b39-bf3f120a4262.png)

**Comment by evermoreobsolete** [comment]
This is a wider issue as the crafting table screen should close when a player goes out of range of the table. I've submitted a patch that should reintroduce the range check and in turn should mean this dupe is impossible as the screen closes long before the table is unloaded.

**Comment by fxmorin** [comment]
Has this been fixed or is the change only client-side. If it's only client-side I could attempt to make a fix.

**Comment by altrisi** [comment]
According to #20, that fixed this. I'd assume it's fixed since #20 was merged.
