### ISSUE TITLE
Server with carpet-autoCraftingTable kicks users after joining

### ISSUE THREAD

**Issue by Floris0106** [gnembon/carpet-autoCraftingTable#2]
An error is left to the player:
`Registry remapping failed: Received ID map for minecraft:block_entity_type contains IDs unknown to the receiver!`
`- carpet:crafting_table`
This always happens, independent of the autoCraftingTable rule.
The server console is as follows (from a Multicraft server):
`30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: io.netty.channel.unix.Errors$NativeIoException: writevAddresses(..) failed: Connection reset by peer
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.unix.Errors.ioResult(Errors.java:146)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.unix.FileDescriptor.writevAddresses(FileDescriptor.java:155)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytesMultiple(AbstractEpollStreamChannel.java:316)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteMultiple(AbstractEpollStreamChannel.java:523)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:434)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:398)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at java.lang.Thread.run(Thread.java:748)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: io.netty.channel.unix.Errors$NativeIoException: writevAddresses(..) failed: Connection reset by peer
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.unix.Errors.ioResult(Errors.java:146)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.unix.FileDescriptor.writevAddresses(FileDescriptor.java:155)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytesMultiple(AbstractEpollStreamChannel.java:316)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteMultiple(AbstractEpollStreamChannel.java:523)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:434)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:398)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at java.lang.Thread.run(Thread.java:748)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: io.netty.channel.unix.Errors$NativeIoException: writevAddresses(..) failed: Connection reset by peer
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.unix.Errors.ioResult(Errors.java:146)
30.01 19:21:42 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.unix.FileDescriptor.writevAddresses(FileDescriptor.java:155)
30.01 19:21:43 [Multicraft] Skipped 26620 lines due to rate limit (30/s)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at java.lang.Thread.run(Thread.java:748)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: io.netty.channel.unix.Errors$NativeIoException: writevAddresses(..) failed: Connection reset by peer
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.unix.Errors.ioResult(Errors.java:146)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.unix.FileDescriptor.writevAddresses(FileDescriptor.java:155)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytesMultiple(AbstractEpollStreamChannel.java:316)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteMultiple(AbstractEpollStreamChannel.java:523)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:434)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:398)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at java.lang.Thread.run(Thread.java:748)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: io.netty.channel.unix.Errors$NativeIoException: writevAddresses(..) failed: Connection reset by peer
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.unix.Errors.ioResult(Errors.java:146)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.unix.FileDescriptor.writevAddresses(FileDescriptor.java:155)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytesMultiple(AbstractEpollStreamChannel.java:316)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteMultiple(AbstractEpollStreamChannel.java:523)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:434)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:398)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at java.lang.Thread.run(Thread.java:748)
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: io.netty.channel.unix.Errors$NativeIoException: writevAddresses(..) failed: Connection reset by peer
30.01 19:21:43 [Server] Netty Epoll Server IO #15/INFO [STDERR]: at io.netty.channel.unix.Errors.newIOException(Errors.java:122)`
The server runs the following mods:
- SimpleHarvest 1.0.4
- Carpet autoCraftingtable 1.3.0
- Carpet Extra 1.3.5
- Everything is a hat 1.0.4
- Fabric API 0.4.29 Build 290
- Fabric Carpet 1.3.6
- G4mespeed 1.0.4
- hopperOptimizations 0.1.11
- Phosphor 0.3.6

**Comment by DeadlyMC** [comment]
Do u have the fabric api on your client?

**Comment by Floris0106** [comment]
I do, and i now know more about the problem (thanks to gnembon). I'm trying to avoid it altogether by getting a replacement for SimpleHarvest that doesn't require fabric api.

**Comment by gnembon** [comment]
you can try replacing the crafting table with crafting dropper that does not cause these problems. It is in carpet-extra

**Comment by Floris0106** [comment]
I've just figured out that now that i've updated carpet and carpet extra this problem only persists when using multiconnect

**Comment by Earthcomputer** [comment]
1. Your original post did not state that you had multiconnect installed.
1. Carpet is not a clientside-only mod, and is therefore not supported by multiconnect, that is not even conceptually possible.
