### ISSUE TITLE
[Question] When are you updating this to 1.17?

### ISSUE THREAD

**Issue by gwoonryan** [gnembon/carpet-autoCraftingTable#24]
is this gonna be udpated to the 1.17 snapshots... i really want to use this for 21w11a! :)

**Comment by altrisi** [comment]
Is the current snapshot release broken? If so, do you have a crash report?

**Comment by SeaSloth** [comment]
[crash-2021-03-29_19.52.41-server.txt](https://github.com/gnembon/carpet-autoCraftingTable/files/6250475/crash-2021-03-29_19.52.41-server.txt)
This is the crash report from my 21w11a server.

**Comment by gwoonryan** [comment]
can you please send me the link to the snapshot release, i cant find it

**Comment by JackTGG** [comment]
either I cant find the version or nothing has changed with the code here and it works.

**Comment by altrisi** [comment]
The latest snapshot version was for 20w46a, available as the last file in the releases page, I haven't tested it myself though, so if people say it doesn't work, an issue saying "doesn't work in [version]" should be filled instead.

**Comment by altrisi** [comment]
Code has been pushed for 21w18a, may work in newer versions. You can get the development builds from the artifacts in the last [Github Actions run](https://github.com/gnembon/carpet-autoCraftingTable/actions/workflows/devbuild.yml) (the jar without `-dev` or `-sources` suffix).

**Comment by altrisi** [comment]
And it has already been released for 1.17. This issue should be closed IMO.
