### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by codemonkey76** [gnembon/carpet-autoCraftingTable#55]
When can we expect 1.19 support?

**Comment by Yadokingu** [comment]
@Crec0 could you maybe fork this and implement the fixes? With the missing update to 1.18.2 and this not being updated to 1.19 for over a week, after carpet and carpet-extra were updated, it rather seems like @gnembon has abandoned it. Maybe related to this comment: https://github.com/gnembon/carpet-autoCraftingTable/issues/42#issuecomment-1012133654

**Comment by Crec0** [comment]
I dont think gnembon abandoned it. He is just busy and autocrafting table is not as high priority project as carpet. 
As for fixes, which fixes are we talking about specifically ?

**Comment by Yadokingu** [comment]
> I dont think gnembon abandoned it. He is just busy and autocrafting table is not as high priority project as carpet. As for fixes, which fixes are we talking about specifically ? If you want to go more in-depth, ping me in Carpet discord.

I just meant the lag fix to the recipe manager and update to 1.19.
No updates for over half a year, when an update would only require authorising a pull request, and his other mods getting updated within hours, seems pretty abandoned to me. It's not like he owes us anything, but I think we should be realistic here. There is no update coming.

**Comment by Crec0** [comment]
Have you tried using #56 yet?
