### ISSUE TITLE
Shift Clicking a recipe from the crafting table will craft something else using the items that remain.

### ISSUE THREAD

**Issue by NikoUY** [gnembon/carpet-autoCraftingTable#6]
For example if you craft a Smithing Table with extra iron in the crafting grid you will get a bunch of pressure plates, I suppose that the reason why this is happening is because that is the way it works if you are auto crafting using a hopper but I feel like this shouldn't apply to the normal crafting system.

**Comment by Megaminx12** [comment]
Confirmed 1.16.3 with gold ----> gold blocks. Also produces nuggets with the leftover gold.

**Comment by eamondo2** [comment]
Can confirm that the issue still exists as of MC1.18 release, and latest Fabric etc.
