### ISSUE TITLE
Autocrafting table update to 1.19.3?

### ISSUE THREAD

**Issue by johnnygoboy** [gnembon/carpet-autoCraftingTable#62]
Just to confirm the current build does not run on 1.19.3, just wondered when we can expect an update?

thanks for this awesome mod.

**Comment by QPCrummer** [comment]
Till this gets updated, you could potentially use my mod: https://modrinth.com/mod/fabricautocrafter

It has the same features as this autocrafter, but doesn’t override vanilla crafting tables. Instead it adds its own new block (though still vanilla compatible). You can craft my autocrafter with a crafting table surrounded by redstone dust. I hope this is helpful 👍

**Comment by johnnygoboy** [comment]
Thank you. Good shout.

**Comment by johnnygoboy** [comment]
thank you Crec0

**Comment by altrisi** [comment]
This was fixed by #63 and can be closed now.
